### ISSUE TITLE
How to copy/clone visual composer structure to new language

### ISSUE THREAD

**Issue by vitalyiegorov** [WPGlobus/wpglobus-for-wpbakery-visual-composer#2]
I have finished page creation with visual composer, then installed wpglobus and wpglobus for visual composer and now i have two tabs in page editor - one is filled with my previous structure - other is empty.

Is there a way to copy existing structure to new language? Right now same visual composer structure is showed on both languages on the web-site

@tivnet @alexgff

**Comment by alexgff** [comment]
@vitalyiegorov 
First of all don't forget to make backup before start.
You can use Text mode of tinymce editor to copy/paste to second tab. 
Then make changes for extra language.
